# config.yml - Low Carbon Heating Roadmap for Madrid
project:
  name: Low-Carbon-Heating-Roadmap-for-Madrid
  owner: MBengochea
  contact: ""

data:
  raw_dir: data/raw
  processed_dir: data/processed
  artifacts_dir: artifacts
  audit_dir: data/ingest_audit

defaults:
  adoption_rate_default: 0.30         # default adoption rate if missing
  priority_districts: [10, 11, 12, 13, 15]  # Latina, Carabanchel, Usera, Puente, Ciudad Jardín
  currency: "EUR"
  money_format: "€{value:,.0f}"       # formatting applied by src/formatting
  co2_unit: "tons/yr"

optimization:
  solver: "greedy"                    # options: greedy, lp_relaxed, mip (recommend mip for final)
  budget_eur_default: 90000000
  capex_subsidy_pct_default: 0.0
  opex_factor_default: 1.0
  co2_factor_default: 1.0
  priority_first: true

modeling:
  random_seed: 42
  train_val_test_split: [0.6, 0.2, 0.2]
  candidate_models:
    - "logistic_regression"
    - "random_forest"
    - "xgboost"
  metrics:
    - "auc"
    - "precision_at_k"
    - "calibration_brier"

artifacts:
  pareto_frontier: artifacts/pareto_frontier.csv
  adoption_model_pickle: models/adoption_model.pkl
  model_card: models/model_card.json

git:
  branch_strategy: "main + feature/*"
  commit_frequency_recommendation: "daily"

notes:
  - "All monetary values are integers in euros in processed data; formatting for stakeholders applied at reporting stage."
  - "Adoption rate default is configurable. Document any district-specific overrides in data/ingest_audit/*.json."
